name: Compress and Deploy JS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout des Repositorys
    - name: Checkout code
      uses: actions/checkout@v3

    # Node.js installieren
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Abhängigkeiten installieren
    - name: Install dependencies
      run: npm install terser --save-dev

    # JavaScript-Datei komprimieren
    - name: Compress JS
      run: npx terser src/datetime-picker.js -o dist/datetime-picker.min.js

    # Komprimierte Datei auf GitHub Pages bereitstellen
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
